<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-UNO4ULJI" failures="1" tests="3" name="Default test(failed)(failed)" time="6.894" errors="0" timestamp="2022-10-21T13:59:05 IST">
  <testcase classname="TestCases.failedTest" name="loginToApp2Test" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [null] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [false]
at TestCases.failedTest.loginToApp2Test(failedTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginToApp2Test -->
  <testcase classname="TestCases.failedTest" name="verifyloginLogoTest" time="0.056"/>
  <testcase classname="TestCases.failedTest" name="verifybotLogoTest" time="0.034"/>
  <testcase classname="TestCases.failedTest" name="verifyTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleTest -->
  <testcase classname="TestCases.failedTest" name="loginToAppTest" time="0.0">
    <ignored/>
  </testcase> <!-- loginToAppTest -->
  <testcase classname="TestCases.failedTest" name="verifyurlTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyurlTest -->
</testsuite> <!-- Default test(failed)(failed) -->
